export {default as Container} from './Container';
export {default as Navbar} from './Navbar';
export {default as Hero} from './Hero';
export {default as AboutUs} from './AboutUs';
export {default as Menu} from './Menu';
export {default as Chef}from './Chef';
export {default as Intro}from './Intro';
export {default as Awards}from './Awards';
export {default as Gallery}from  './Gallery';
export {default as FindUs}from './FindUs';
export {default as NewLetters}from './NewLetters';
export {default as Footer}from './Footer';